name: riemann-adelic
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=2.3.3
  - mpmath=1.3.0
  - sympy=1.14.0
  - matplotlib=3.9.2
  - jupyter=1.1.1
  - nbconvert=7.16.6
  - requests=2.31.0
  - pytest=8.4.2