name: riemann-adelic
channels:
  - conda-forge
dependencies:
  - python=3.11
  - mpmath=1.3.0
  - numpy=1.26.4
  - scipy=1.13.0
  - sympy=1.12
  - matplotlib=3.8.2
  - jupyter=1.0.0
  - requests=2.32.0
  - pytest=8.2.0
  - pip
  - pip:
    - nbconvert==7.16.4