name: Build and Validate

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full
          pip install -r requirements.txt
          pip install nbconvert jupyter mpmath sympy
      - name: Compile LaTeX
        run: |
          cd paper
          # Check if pdflatex is available, otherwise skip compilation
          if command -v pdflatex &> /dev/null; then
            pdflatex main.tex
            echo "✅ LaTeX compiled successfully"
          else
            echo "⚠️ pdflatex not found, skipping LaTeX compilation"
            touch main.pdf  # Create dummy file for artifact upload
          fi
      - name: Execute Notebook with Increased Timeout
        run: |
          mkdir -p docs
          jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1800 notebooks/validation.ipynb --output ../docs/validation_executed.ipynb
          jupyter nbconvert --to html docs/validation_executed.ipynb --output validation.html
        env:
          PYTHONUNBUFFERED: 1
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: paper-output
          path: |
            paper/main.pdf
            docs/validation.html