name: Build and Validate

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45  # Increased job timeout for robustness
    steps:
      - uses: actions/checkout@v4  # Use latest version for consistency
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Setup Environment and Download Data
        run: |
          mkdir -p zeros
          # Try repo source first, fallback to Odlyzko with firewall handling
          curl -L -o zeros/zeros_t1e8.txt https://github.com/motanova84/-jmmotaburr-riemann-adelic/raw/main/zeros/zeros_t1e8.txt || \
          curl -L -o zeros/zeros_t1e8.txt https://www-users.cse.umn.edu/~odlyzko/zeta_tables/zeros1 || \
          echo "Warning: Could not download precomputed zeros. Using fallback or local file if available."
          sudo apt-get update -qq  # Quiet mode for cleaner logs
          sudo apt-get install -y texlive-full
          pip install -r requirements.txt
          pip install nbconvert jupyter mpmath sympy numpy requests pytest
      - name: Compile LaTeX
        run: |
          cd paper
          pdflatex -interaction=nonstopmode main.tex || { echo "LaTeX compilation failed"; exit 1; }
          # Second pass for cross-references
          pdflatex -interaction=nonstopmode main.tex || { echo "Second LaTeX pass failed"; exit 1; }
      - name: Execute Notebook with Optimized Timeout
        run: |
          export PYTHONUNBUFFERED=1
          export PRIME_COUNT=100
          export PRIME_POWERS=5  # Added from copilot branch
          export ZERO_COUNT=100
          export INTEGRATION_T=10
          mkdir -p docs
          jupyter nbconvert --to html --execute --ExecutePreprocessor.timeout=1800 \
            --ExecutePreprocessor.kernel_name=python3 \
            notebooks/validation.ipynb --output-dir docs --output validation.html
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4  # Updated from v3 to v4
        if: always()  # Ensure artifacts are uploaded even on failure
        with:
          name: paper-output
          path: |
            paper/main.pdf
            docs/validation.html
          retention-days: 30  # Added from copilot branch for better artifact management
      - name: Check Execution Time and Errors
        if: failure()
        run: |
          echo "Execution failed. Check logs for details."
          ls -la docs/ || echo "Docs directory empty"
          cat docs/validation.html 2>/dev/null || echo "HTML not generated"