name: Dependency Review

# Workflow para revisar cambios en dependencias en cada Pull Request
# Ayuda a detectar vulnerabilidades de seguridad y licencias problemáticas
on:
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Review Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        # Opciones de configuración:
        # fail-on-severity: moderate  # Falla en vulnerabilidades moderadas o superiores
        # deny-licenses: GPL-3.0, AGPL-3.0  # Licencias a rechazar
        # allow-licenses: MIT, Apache-2.0, BSD-3-Clause  # Solo permite estas licencias
        
        # Configuración recomendada para empezar:
        fail-on-severity: high
        comment-summary-in-pr: true
        
    # ============================================================
    # INSTRUCCIONES PARA EL MANTENEDOR:
    # 
    # 1. Este workflow solo se ejecuta en PRs para revisar cambios en:
    #    - requirements.txt
    #    - package.json
    #    - go.mod
    #    - Cargo.toml
    #    etc.
    # 
    # 2. Ajusta fail-on-severity según tu política:
    #    - low: Muy estricto, puede generar muchas alertas
    #    - moderate: Equilibrado
    #    - high: Solo vulnerabilidades serias
    #    - critical: Solo las más graves
    # 
    # 3. Considera añadir deny-licenses si tienes restricciones
    # 
    # 4. Para Python, considera también:
    #    - pip-audit para auditoría de seguridad
    #    - safety check
    # ============================================================
