name: Lean4 Formalization

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  lean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Lean 4
        uses: leanprover/lean-action@v1
        with:
          lean-version: "leanprover/lean4:stable"

      - name: Build project
        run: |
          cd formalization/lean
          lake build

      - name: Run Lean tests
        run: |
          cd formalization/lean
          lake exe tests || echo "No test target found"