name: Lean Formalization

on:
  push:
    paths:
      - 'formalization/lean/**'
      - '.github/workflows/lean.yml'
  pull_request:
    paths:
      - 'formalization/lean/**'
      - '.github/workflows/lean.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Lean
      uses: leanprover/lean-action@v1
      with:
        lean-version: "leanprover/lean4:latest"

    - name: Install dependencies
      run: |
        lake update

    - name: Compile Lean formalization
      run: |
        cd formalization/lean
        lake build

    - name: Run Lean check
      run: |
        cd formalization/lean
        lake exe cache get
        lake exe check RH_final.lean