name: Lean4 Formalization

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lean-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Lean4
        uses: leanprover/lean-action@v1
        with:
          lean-version: "leanprover/lean4:stable"

      - name: Build Lean formalization
        run: |
          cd formalization/lean
          lake exe cache get
          lake build