# Property-based tests: ejecuta Hypothesis para encontrar casos corner.
# Hypothesis es una biblioteca de testing basado en propiedades para Python
name: Property Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  property-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-hypothesis-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-hypothesis-
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install hypothesis pytest

      - name: Run property-based tests
        run: |
          # Ejecutar tests que usan Hypothesis con más ejemplos
          pytest tests/ -v --tb=short -k "property or hypothesis" --hypothesis-show-statistics || echo "No property-based tests found, skipping"

      - name: Run Hypothesis with extended examples
        run: |
          # Si existen tests con Hypothesis, ejecutarlos con más ejemplos
          HYPOTHESIS_PROFILE=ci pytest tests/ -v --tb=short || echo "Property tests completed or not found"
        env:
          HYPOTHESIS_PROFILE: ci
