name: Operator Validation

on:
  push:
    branches: [ main, develop, copilot/** ]
  pull_request:
    branches: [ main ]

jobs:
  test-operator:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install numpy scipy pytest

      - name: Run basic operator tests
        run: |
          pytest -v operador/tests_operador.py

      - name: Run extended tests with output
        run: |
          pytest -s operador/tests_operador_extended.py > convergence.log

      - name: Upload convergence table
        uses: actions/upload-artifact@v4
        with:
          name: convergence-table
          path: convergence.log
