name: Run Tests Only

on:
  push:
    branches: [ main, develop, copilot/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run validation tests
        run: |
          echo "🧮 Running Riemann Hypothesis validation tests"
          python validate_v5_coronacion.py --precision 15
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            data/
            logs/
          retention-days: 30