name: Operator Validation

on:
  push:
    branches: [ main, develop, copilot/** ]
  pull_request:
    branches: [ main ]

jobs:
  test-operator:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-14 llvm-14-dev libigraph-dev libigraph3t64

      - name: Install dependencies
        env:
          NUMEXPR_MAX_THREADS: 4
          NUMEXPR_NUM_THREADS: 2
        run: |
          python -m pip install --upgrade pip==24.3.1
          pip install -r requirements-lock.txt

      - name: Run basic operator tests
        run: |
          pytest -v operador/tests_operador.py

      - name: Run extended tests with output
        run: |
          pytest -s operador/tests_operador_extended.py > convergence.log

      - name: Upload convergence table
        uses: actions/upload-artifact@v4
        with:
          name: convergence-table
          path: convergence.log
